version: "3.8"
services:
  postgresSQL:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banknet

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports: ["2181:2181"]
    networks:
      - banknet

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - banknet

  user-service:
    build: ../user-service
    depends_on:
      - postgresSQL
      - kafka
    networks:
      - banknet
    ports:
      - "8081:8081"

  gateway-service:
    build: ../gateway-service
    depends_on:
      - user-service
      - account-service
      - kafka
    networks:
      - banknet
    ports:
      - "8080:8080"

  account-service:
    build: ../account-service
    depends_on:
      - postgresSQL
      - kafka
    networks:
      - banknet
    ports:
      - "8082:8082"

networks:
  banknet:
    driver: bridge

volumes:
  pgdata:
